### ISSUE TITLE
Añadir usuario a empresa

### ISSUE THREAD

**Issue by AntonioSillero** [i62lotor/sgf-testing#2]
Al hacer un POST a /companies/2/appUsers con rol administrador con los datos:
{
  "company": 2,
  "email": "otroemail@otro.local",
  "firstSurname": "Apellido1",
  "name": "Pepe",
  "password": "pepepasswd",
  "phone": "123456",
  "role": "USER",
  "secondSurname": "Apellido2",
  "status": "ACTIVE",
  "username": "pepe"
}
Responde correctamente 201 pero los datos no aparecen en la tabla app_users.

Si se intenta hacer de nuevo la petición la respuesta es 409 y los datos:
{"exception":"es.geocoding.sgf.exception.ResourceAlreadyExistsException","path":"/companies/2/appUsers","error":"CONFLICT","message":"AppUser with username luis already exists","timestamp":1507399485571,"status":409}

Si detenemos la aplicación tampoco aparecen los datos en la tabla. Falta un COMMIT?

**Comment by AntonioSillero** [comment]
Ocurre los mismo al crear un usuario desde 
POST /appUsers/

De manera que después tampoco se puede modificar el usuario creado con 
PUT /appUsers/{id}
genera una excepción:
"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction"

**Comment by i62lotor** [comment]
He probado en development y con H2 funciona correctamente. 
Voy a probar con postgis

**Comment by i62lotor** [comment]
También funciona correctamente en postgis. Los usuarios se guardan correcamente en la base de datos.
