### ISSUE TITLE
Cambiar password a un usuario

### ISSUE THREAD

**Issue by AntonioSillero** [i62lotor/sgf-testing#3]
Al hacer un 
PUT /appUsers/{id}/password
qué datos hay que enviar?

He probado con 
{
	"password": "12345678"
}

La documentación de la API no me queda clara.

Por otra parte no hay datos de respuesta del servicio. Código de respuesta 204.

**Comment by i62lotor** [comment]
Vale, parece que swagger-ui no ha generado correctamente la documentación para ese recurso.
El json que se envía es tal y como tu lo pones.
La respuesta 204 es correcta (NO_CONTENT). La petición ha sido procesada correctamente, pero no es necesario enviar contenido en la respuesta.
