### ISSUE TITLE
Problema al crear empresa

### ISSUE THREAD

**Issue by AntonioSillero** [i62lotor/sgf-testing#5]
Al hacer un POST a /companies/
con los datos:

{
  "cif": "companicif4Ed",
  "email": "string@domain.local",
  "id": 1,
  "name": "string",
  "phones": [
    "string"
  ],
  "postalCode": "PC4Ed",
  "status": "ACTIVE",
  "web": "www.4Ed.loca"
}

Respuesta:

{"cif":"companicif4Ed","name":"string","postalCode":"PC4Ed","email":"string@domain.local","web":"www.4Ed.loca","status":"ACTIVE","phones":["string"],"_links":{"self":{"href":"http://localhost:8080/companies/1"}}}

(el id:1 ya estaba en la base de datos) Indica que la operación se ha realizado correctamente pero a partir de ese momento ya no puedo hacer login. 

Respuesta al login:

{"timestamp":1507455136206,"status":401,"error":"Unauthorized","message":"Authentication Failed: Bad credentials","path":"/login"}

**Comment by i62lotor** [comment]
El json a enviar de compañía puede ser bastante complejo. Es debido a que se usa la misma entidad persistente.
El id no se debaría enviar, ya que es autogenerado a la hora de guardar. La única comprobación actual es por CIF.
Para un futuro podemos plantear el dejar de usar las entidades persistentes, y simplificar el modelo de intercambio.

**Comment by AntonioSillero** [comment]
Lo que me preocupa es que al poner yo el id 1 ya no puedo hacer login... por eso lo he etiquetado como bug.

**Comment by i62lotor** [comment]
No he podido reproducir el error.  Lo probare mas tranquilamente.

**Comment by i62lotor** [comment]
Comprobado. Existe un bug.
¡Bien hecho!

**Comment by i62lotor** [comment]
Solucionado. Pendiente de aprobación del PR.
