### ISSUE TITLE
Inestabilidad al crear empresas?

### ISSUE THREAD

**Issue by AntonioSillero** [i62lotor/sgf-testing#6]
Se han realizado las siguientes peticiones:
Petición 1: POST http://localhost:8080/companies/

POST data:
{
  "cif": "companicifpNf",
  "email": "string@domain.local",
  "id": null,
  "name": "string",
  "phones": [
    "string"
  ],
  "postalCode": "PCpNf",
  "status": "ACTIVE",
  "web": "www.pNf.loca"
}

Respuesta 1: 
{"cif":"companicifpNf","name":"string","postalCode":"PCpNf","email":"string@domain.local","web":"www.pNf.loca","status":"ACTIVE","phones":["string"],"_links":{"self":{"href":"http://localhost:8080/companies/7"}}}

-------------------------------------------------------------------

Petición 2: PUT http://localhost:8080/companies/7

PUT data:
{
  "cif": "newcompanicifpNf",
  "email": "newstring@domain.local",
  "id": null,
  "name": "newstring",
  "phones": [
    "newstring"
  ],
  "postalCode": "NewPCpNf",
  "status": "ACTIVE",
  "web": "www.newpNf.loca"
}

Respuesta 2:

{"cif":"newcompanicifpNf","name":"newstring","postalCode":"NewPCpNf","email":"newstring@domain.local","web":"www.newpNf.loca","status":"ACTIVE","phones":["newstring"],"_links":{"self":{"href":"http://localhost:8080/companies/7"}}}

----------------------------------------------------------------------------------
Petición 3:  POST http://localhost:8080/companies/

POST data:
{
  "cif": "companicifJWT",
  "email": "string@domain.local",
  "id": null,
  "name": "string",
  "phones": [
    "string"
  ],
  "postalCode": "PCJWT",
  "status": "ACTIVE",
  "web": "www.JWT.loca"
}

Respuesta 3:
{"cif":"companicifJWT","name":"string","postalCode":"PCJWT","email":"string@domain.local","web":"www.JWT.loca","status":"ACTIVE","phones":["string"],"_links":{"self":{"href":"http://localhost:8080/companies/8"}}}

-------------------------------------------------------

Petición 4: PUT http://localhost:8080/companies/8

PUT data:
{
  "cif": "newcompanicifJWT",
  "email": "newstring@domain.local",
  "id": null,
  "name": "newstring",
  "phones": [
    "newstring"
  ],
  "postalCode": "NewPCJWT",
  "status": "ACTIVE",
  "web": "www.newJWT.loca"
}

Respuesta 4: 
{"timestamp":1507566696587,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.DataIntegrityViolationException","message":"could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement","path":"/companies/8"}
---------------------------------------------------------------------------

Petición 5:  POST http://localhost:8080/companies/

POST data:
{
  "cif": "companicif6qW",
  "email": "string@domain.local",
  "id": null,
  "name": "string",
  "phones": [
    "string"
  ],
  "postalCode": "PC6qW",
  "status": "ACTIVE",
  "web": "www.6qW.loca"
}

Respuesta 5:
{"timestamp":1507566706671,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.DataIntegrityViolationException","message":"could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement","path":"/companies/"}

A partir de este momento no se pueden crear empresas a no ser que se borren las anteriores.

**Comment by i62lotor** [comment]
El error en la petición 4 no consigo reproducirlo, en mi caso si que funciona.
En la petición 5 parece que se está violando la restricción de clave única para el nombre (name).
En mis pruebas si que se especifica en el mensaje de la respuesta:


```
    {
        "timestamp": 1507583592848,
        "status": 500,
        "error": "Internal Server Error",
        "exception": "org.springframework.dao.DataIntegrityViolationException",
        "message": "could not execute statement; SQL [n/a]; constraint ["COMPANY_NAME_UK_INDEX_5 ON PUBLIC.COMPANIES(NAME) VALUES ('string', 3)"; SQL statement:
    insert into companies (id, cif, email, name, postal_code, status, web) values (null, ?, ?, ?, ?, ?, ?) [23505-196]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
        "path": "/companies/"
    }


```



El mensaje del error no es descriptivo, pero el sistema parece que hace lo que debe hacer. Supongo que en la consola donde se esté ejecutando el servicio dará mas información

**Comment by AntonioSillero** [comment]
Correcto!
