### ISSUE TITLE
Creación de vehiculos dentro de una empresa

### ISSUE THREAD

**Issue by AntonioSillero** [i62lotor/sgf-testing#8]
Puedo hacer un post a  http://localhost:8080/companies/1/vehicles

con los datos:
{
  "comments": "Vehiculo eTb",
  "id": null,
  "kmsLeftForRevision": 0,
  "lastRevisionDate": "2017-10-08",
  "name": "eTb",
  "plate": "eTbeTbeTb",
  "status": "ACTIVE",
    "company": {
    "id": 2
  },
    "model": {
    "id": 1,
       "make": {
      "id": 29
       }
  },
  "type": {
    "id": 9
  }
}

El vehiculo se añade a company 2... No se si puede ser confuso...

**Comment by i62lotor** [comment]
Eso seria un bug.
Lo revisamos en cuanto se pueda.

**Comment by i62lotor** [comment]
Efectivamente esa manera de funcionar con es muy coherente.
Actualmente solo podría suceder para un Administrador de la plataforma, para un administrador de empresa no lo deja, pero el mensaje que devuelve es un 403 (prohibido), como si no tuviese acceso al recurso, cuando en realidad creo que debería de ser un bad request.

**Comment by i62lotor** [comment]
La funcionalidad dará preferencia al identificador especificado en la URL.
